require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 3.0.2
  NewCops: enable

Style/Documentation:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - for
    - when
    - with
    - without

Rails/FilePath:
  Enabled: false

Metrics/MethodLength:
  AllowedMethods:
    - execute
    - prepare_variables

Naming/MethodParameterName:
  AllowedNames:
    - e